# Generated by Django 5.1.7 on 2025-03-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.CharField(max_length=255)),
                ('auth_url', models.CharField(max_length=255)),
                ('graphql_url', models.CharField(max_length=255)),
            ],
        ),
    ]
